import './globals.css'
import '../styles/global.css'
import '@repo/ui/styles.css'
import type { Metadata } from 'next'
import { Sidebar, NavBar, NavBarData } from '@repo/ui'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body
        className={`flex ${montserrat.className} grid grid-cols-1 md:grid-cols-[320px_auto] h-screen`}
      >
        <Sidebar />
        <div className="bg-white text-black">{children}</div>
        <NavBar navBarData={NavBarData} />
      </body>
    </html>
  )
}
