#!/usr/bin/env sh

echo '\n1️⃣ Running ESLint checks before commit\n'

pnpm run lint ||
(
    echo '\n❌Oops! Seems there are some eslint errors in the above files! ⬆️ ⬆️ ⬆️ \n\n Run "npm run lint:fix" to fix those, stage them and try commit again.😇\n';
    false;
)
 
echo '\n✅ESLint checks passed. proceeding to Prettier Check.\n'

echo '2️⃣ Running Prettier check before commit'

npm run check-format ||
(
    echo '\n❌Oops! Seems the above files are not formatted! ⬆️ ⬆️ ⬆️ \n\n Run "npm run format" to format them, stage them and try commit again.😇\n';
    false;
)
 
echo '\n✅Prettier checks passed. proceeding to commit.\n'