#!/usr/bin/env sh

echo 'Running Prettier check before commit'

npm run check-format ||
(
    echo '\n❌ Oops! Seems the above files are not formatted! ⬆️⬆️⬆️ \n\n Run "npm run format" to format them, stage them and try commit again.😇\n';
    false;
)
 
echo '\n✅Precommit checks passed. proceeding to commit.\n'